### ISSUE TITLE
Add Springer Templates

### ISSUE THREAD

**Issue by stevejpurves** [myst-templates/templates#12]
https://www.springernature.com/gp/authors/campaigns/latex-author-support

**Comment by dressedfez** [comment]
I will have a look at this. PR towards beginning of the coming week.

**Comment by rowanc1** [comment]
So cool! Thank you @dressedfez! :)

**Comment by dressedfez** [comment]
Initial version which still needs some work can be found here: https://github.com/dressedfez/springer

**Comment by dressedfez** [comment]
@rowanc1 and @stevejpurves shall we close this issue?

**Comment by rowanc1** [comment]
🚀 Nice! Yes. :)
