### ISSUE TITLE
should `myst-templates` cli global install give the access to the miniCLI?

### ISSUE THREAD

**Issue by stevejpurves** [myst-templates/templates#26]
It's possible to globally install something called `myst-templates` from npm, i.e.

```
npm i -g myst-templates
```

succeeds, installs something but the `myst-templates --help` gives command not found. 

Expectation after not reading the readme properly was that I would have the miniCLI available.

**Comment by stevejpurves** [comment]
or perhaps this is not meant for contributors to be running at all? see #27

**Comment by rowanc1** [comment]
The myst-templates is not a CLI, it is a library that is used in `jtex` and the `myst-cli`. Is there somewhere where we documented that incorrectly?

**Comment by rowanc1** [comment]
I think I see the problem -- there was a clash in package/cli names. I have updated the action in #29. This is a private package that just does the indexing.

You can use it with a `npm run link` and then the command is now `myst-templates-api` which should remove confusion going forward!
