### ISSUE TITLE
are tex contributing instructions correct?

### ISSUE THREAD

**Issue by stevejpurves** [myst-templates/templates#27]
Following the instructions on the README for a new tex temple I see the following sequence of events:

1. update `data/tex.yml` - fine
2. get the cli installed `npm install` and `npm run dev` and CTRL+C
3. run `myst-templates index data/tex.yml` - this errors out

```
Cloning https://github.com/myst-templates/cageo to _build/tex/myst/cageo/main
The path "readme/profile/README.md" does not exist and cannot update the organization README.
Try "git clone git@github.com:myst-templates/.github.git readme" to create the relevant folder
```

5. run `git clone git@github.com:myst-templates/.github.git readme` which gets me a new folder
6. re-run `myst-templates index data/tex.yml` - which now works

But now i have a new folder and readme file for the myst-templates organisation that I do not think I should be submitting.?

what should I be committing in order to submit my PR? only the `data/tex.yml` changes and the other steps are actually done in CI and not by me?

**Comment by rowanc1** [comment]
Correct, the Readme is update in CI, you should only edit the `data/tex.yml`, the rest should happen automatically on CI.

**Comment by rowanc1** [comment]
I have updated a few things to make it clearer I think?

There is now some more CI in #30, and in #29 I changed to `myst-tempaltes-api` which should be clearer that this is the local package!

**Comment by stevejpurves** [comment]
👍🏼 gotcha - see https://github.com/myst-templates/templates/pull/31 for some addn suggestions
